(ns triangle.wgpu
  "WebGPU for the triangle demo, on the full wgpu-native bindings that
  jextract generated from webgpu.h plus the wgpu-native extensions in
  wgpu.h (wgpu-native 22.1.0.5): package wgpu under java/, made and
  regenerated by regenerate-bindings.sh.

  This namespace is the demo half of the interop: the struct builders
  for the descriptors the demo fills, the two WGSL shaders, the vertex
  data conversion and the per-frame helpers. Each C struct is allocated
  with the layout jextract derived from the header (StructName/allocate)
  and filled through the generated per-field setters, so the byte
  layout cannot drift from the header. Unset members stay zero, which
  is what the C API expects for them: NULL pointers, zero counts, and
  the default enum values that live at 0.

  Handles cross the FFM boundary as opaque values: either a raw long
  address or a MemorySegment; ffi/pointer wraps both. The native
  library must be loaded first with triangle.ffi/load-libraries!,
  which also hands the bindings their symbol lookup."
  (:require [clojure.test :refer [deftest is testing]]
            [triangle.ffi :as ffi])
  (:import [java.lang.foreign Arena MemorySegment]
           [wgpu WGPUBufferDescriptor WGPUChainedStruct WGPUColor
            WGPUFragmentState WGPUMultisampleState WGPUPrimitiveState
            WGPURenderPassColorAttachment WGPURenderPassDescriptor
            WGPURenderPipelineDescriptor WGPUSurfaceConfiguration
            WGPUSurfaceDescriptor WGPUSurfaceDescriptorFromMetalLayer
            WGPUSurfaceDescriptorFromWaylandSurface
            WGPUSurfaceDescriptorFromWindowsHWND
            WGPUSurfaceDescriptorFromXlibWindow WGPUSurfaceTexture
            WGPUShaderModuleDescriptor WGPUShaderModuleWGSLDescriptor
            WGPUVertexAttribute WGPUVertexBufferLayout WGPUVertexState
            WGPUColorTargetState wgpu_h]))

;; ── enum values (webgpu.h)
;;
;; jextract renders each enum constant as a zero-argument static
;; getter on wgpu_h, which Clojure would read as a field, so they are
;; pulled through reflection once and bound under descriptive names.

(defn- wgpu-constant
  "A wgpu_h enum constant, by the header's spelling."
  [name]
  (let [method (first (filter #(= (.getName %) name)
                              (.getMethods (Class/forName "wgpu.wgpu_h"))))]
    (when-not method
      (throw (ex-info (str "no enum constant named " name " in the generated bindings")
                      {:constant name})))
    (int (.invoke method nil (into-array Object ())))))

(def surface-descriptor-s-type
  "WGPUSType tags for the per-platform surface descriptors."
  {:cocoa (wgpu-constant "WGPUSType_SurfaceDescriptorFromMetalLayer")
   :windows (wgpu-constant "WGPUSType_SurfaceDescriptorFromWindowsHWND")
   :x11 (wgpu-constant "WGPUSType_SurfaceDescriptorFromXlibWindow")
   :wayland (wgpu-constant "WGPUSType_SurfaceDescriptorFromWaylandSurface")})

(def shader-module-s-type
  "WGPUSType_ShaderModuleWGSLDescriptor."
  (wgpu-constant "WGPUSType_ShaderModuleWGSLDescriptor"))

(def ^:private bgra8-unorm-srgb
  "WGPUTextureFormat value. If the triangle comes out black on a machine
  where this format is unsupported, try 0x17 (B8G8R8A8Unorm) or query
  wgpuSurfaceGetCapabilities."
  (wgpu-constant "WGPUTextureFormat_BGRA8UnormSrgb"))

(def ^:private render-attachment-usage
  "WGPUTextureUsage_RenderAttachment | WGPUTextureUsage_CopySrc."
  (bit-or (wgpu-constant "WGPUTextureUsage_RenderAttachment")
          (wgpu-constant "WGPUTextureUsage_CopySrc")))

(def ^:private vertex-buffer-usage
  "WGPUBufferUsage_Vertex | WGPUBufferUsage_CopyDst: the vertex
  shader can read the buffer and queue-write-buffer can fill it."
  (bit-or (wgpu-constant "WGPUBufferUsage_Vertex")
          (wgpu-constant "WGPUBufferUsage_CopyDst")))

(def float32x2-vertex-format
  "WGPUVertexFormat_Float32x2."
  (wgpu-constant "WGPUVertexFormat_Float32x2"))

(def float32x4-vertex-format
  "WGPUVertexFormat_Float32x4."
  (wgpu-constant "WGPUVertexFormat_Float32x4"))

;; ── the WGSL triangle shader
;;
;; No vertex buffers: clip-space positions and per-corner colors are
;; computed from the builtin vertex index. The fragment stage receives
;; the (hardware-interpolated) corner colors and forwards them.

(def triangle-wgsl
  "struct VertexOut {
  @builtin(position) position: vec4<f32>,
  @location(0) color: vec3<f32>,
}

@vertex
fn vertex_main(@builtin(vertex_index) vertex_index: u32) -> VertexOut {
  var out: VertexOut;
  if (vertex_index == 0u) {
    out.position = vec4<f32>(0.0, 0.5, 0.0, 1.0);
    out.color = vec3<f32>(1.0, 0.0, 0.0);
  } else if (vertex_index == 1u) {
    out.position = vec4<f32>(-0.5, -0.25, 0.0, 1.0);
    out.color = vec3<f32>(0.0, 1.0, 0.0);
  } else {
    out.position = vec4<f32>(0.5, -0.25, 0.0, 1.0);
    out.color = vec3<f32>(0.0, 0.0, 1.0);
  }
  return out;
}

@fragment
fn fragment_main(input: VertexOut) -> @location(0) vec4<f32> {
  return vec4<f32>(input.color, 1.0);
}")
(def data-triangle-wgsl
  "struct DataOut {
  @builtin(position) position: vec4<f32>,
  @location(0) color: vec4<f32>,
}

@vertex
fn vertex_data_main(@location(0) position: vec2<f32>,
                    @location(1) color: vec4<f32>) -> DataOut {
  var out: DataOut;
  out.position = vec4<f32>(position, 0.0, 1.0);
  out.color = color;
  return out;
}

@fragment
fn fragment_data_main(input: DataOut) -> @location(0) vec4<f32> {
  return input.color;
}")

;; ── instance, adapter, device

(def ^:private null MemorySegment/NULL)

(defn create-instance!
  "Create the WebGPU instance (the default instance descriptor)."
  []
  (wgpu_h/wgpuCreateInstance null))

(defn first-adapter!
  "Enumerate the instance's adapters (a wgpu-native extension call, not
  core WebGPU) and return the first handle."
  [instance]
  (let [count (wgpu_h/wgpuInstanceEnumerateAdapters (ffi/pointer instance) null null)
        count (long count)]
    (when (zero? count)
      (throw (ex-info "WebGPU enumerated no adapters (missing or headless GPU driver?)"
                      {:adapter-count count})))
    (let [adapters (ffi/pointer-array! (int (min 8 count)))]
      (wgpu_h/wgpuInstanceEnumerateAdapters (ffi/pointer instance) null adapters)
      (let [adapter (ffi/deref-pointer adapters 0)]
        (when-not adapter
          (throw (ex-info "the second wgpuInstanceEnumerateAdapters call filled no slot" {})))
        adapter))))

(defn request-device!
  "Request a device on an adapter. The request is asynchronous: the
  callback resolves a promise, and we wait up to about two seconds for
  it. wgpu-native's processEvents is an unimplemented!() trap under
  X11 (a non-unwinding Rust abort), so we never call it."
  [adapter]
  (let [device-request (promise)
        callback (reify wgpu.WGPUAdapterRequestDeviceCallback$Function
                   (apply [_this status device _message _userdata]
                     (deliver device-request {:status (long status)
                                              :device device})))
        _ (wgpu_h/wgpuAdapterRequestDevice (ffi/pointer adapter) null
                                           (wgpu.WGPUAdapterRequestDeviceCallback/allocate
                                            callback (Arena/global))
                                           null)
        settled (loop [spins (int 0)]
                  (if (or (realized? device-request) (>= spins 1250))
                    (when (realized? device-request) @device-request)
                    (do (Thread/sleep 2)
                        (recur (inc spins)))))]
    (cond
      (nil? settled) (throw (ex-info
                             "device request timed out (no GPU driver to answer?)" {}))
      (not= 0 (:status settled)) (throw (ex-info
                                         (str "wgpuAdapterRequestDevice failed, status "
                                              (:status settled) " (0 means Success)")
                                         {:status (:status settled)}))
      :else (:device settled))))

(defn get-queue
  "wgpuDeviceGetQueue: the queue every submission goes through."
  [device]
  (wgpu_h/wgpuDeviceGetQueue (ffi/pointer device)))

;; ── surfaces

(defn- chain!
  "A WGPUChainedStruct with next = NULL and the given sType tag."
  [s-type]
  (doto (WGPUChainedStruct/allocate (Arena/global))
    (WGPUChainedStruct/sType (int s-type))))

(defn platform-descriptor!
  "Build the per-platform surface struct that chains into
  WGPUSurfaceDescriptor.nextInChain. kind is one of :x11, :wayland,
  :windows or :cocoa; members are that struct's pointer members in
  struct order: display and window for X11, Win32 and Wayland, the
  CAMetalLayer for Cocoa."
  [kind members]
  (case kind
    :cocoa (doto (WGPUSurfaceDescriptorFromMetalLayer/allocate (Arena/global))
             (WGPUSurfaceDescriptorFromMetalLayer/chain
              (chain! (surface-descriptor-s-type :cocoa)))
             (WGPUSurfaceDescriptorFromMetalLayer/layer (ffi/pointer (first members))))
    :windows (doto (WGPUSurfaceDescriptorFromWindowsHWND/allocate (Arena/global))
               (WGPUSurfaceDescriptorFromWindowsHWND/chain
                (chain! (surface-descriptor-s-type :windows)))
               (WGPUSurfaceDescriptorFromWindowsHWND/hinstance (ffi/pointer (first members)))
               (WGPUSurfaceDescriptorFromWindowsHWND/hwnd (ffi/pointer (second members))))
    :x11 (doto (WGPUSurfaceDescriptorFromXlibWindow/allocate (Arena/global))
            (WGPUSurfaceDescriptorFromXlibWindow/chain
             (chain! (surface-descriptor-s-type :x11)))
            (WGPUSurfaceDescriptorFromXlibWindow/display (ffi/pointer (first members)))
            (WGPUSurfaceDescriptorFromXlibWindow/window (long (second members))))
    :wayland (doto (WGPUSurfaceDescriptorFromWaylandSurface/allocate (Arena/global))
                (WGPUSurfaceDescriptorFromWaylandSurface/chain
                 (chain! (surface-descriptor-s-type :wayland)))
                (WGPUSurfaceDescriptorFromWaylandSurface/display (ffi/pointer (first members)))
                (WGPUSurfaceDescriptorFromWaylandSurface/surface (ffi/pointer (second members))))))

(defn surface-descriptor!
  "Build a WGPUSurfaceDescriptor chaining platform-descriptor."
  [platform-descriptor]
  (doto (WGPUSurfaceDescriptor/allocate (Arena/global))
    (WGPUSurfaceDescriptor/nextInChain (ffi/pointer platform-descriptor))))

(defn create-surface!
  "wgpuInstanceCreateSurface with the platform's chained descriptor:
  platform is a GLFW platform keyword, members the pointers of its
  struct (see platform-descriptor!). On X11 the window is an XID
  passed by value (not a Window*), so it travels as a raw long."
  [instance platform members]
  (wgpu_h/wgpuInstanceCreateSurface (ffi/pointer instance)
                                    (surface-descriptor! (platform-descriptor! platform members))))

(defn surface-configuration!
  "Build a WGPUSurfaceConfiguration for a surface of the given pixel
  size: default B8G8R8A8UnormSrgb format, render-target plus copy
  usage, FIFO present mode."
  [device width height]
  (doto (WGPUSurfaceConfiguration/allocate (Arena/global))
    (WGPUSurfaceConfiguration/device (ffi/pointer device))
    (WGPUSurfaceConfiguration/format bgra8-unorm-srgb)
    (WGPUSurfaceConfiguration/usage render-attachment-usage)
    (WGPUSurfaceConfiguration/width (int width))
    (WGPUSurfaceConfiguration/height (int height))
    (WGPUSurfaceConfiguration/presentMode (wgpu-constant "WGPUPresentMode_Fifo"))))

(defn configure-surface!
  "wgpuSurfaceConfigure with surface-configuration!."
  [surface device width height]
  (wgpu_h/wgpuSurfaceConfigure (ffi/pointer surface)
                               (surface-configuration! device width height)))

;; ── shaders, pipelines

(defn shader-module-descriptor!
  "Build a WGPUShaderModuleDescriptor chaining a
  WGPUShaderModuleWGSLDescriptor that names the WGSL source."
  [wgsl-source]
  (doto (WGPUShaderModuleDescriptor/allocate (Arena/global))
    (WGPUShaderModuleDescriptor/nextInChain
     (doto (WGPUShaderModuleWGSLDescriptor/allocate (Arena/global))
         (WGPUShaderModuleWGSLDescriptor/chain
          (chain! shader-module-s-type))
         (WGPUShaderModuleWGSLDescriptor/code (ffi/string! wgsl-source))))))

(defn create-shader-module!
  "Compile the given WGSL source into a shader module on a device."
  [device wgsl-source]
  (wgpu_h/wgpuDeviceCreateShaderModule (ffi/pointer device)
                                       (shader-module-descriptor! wgsl-source)))

(defn color-target-state!
  "Build a WGPUColorTargetState: one colour attachment target, default
  B8G8R8A8UnormSrgb format, default blending, writeMask = All."
  []
  (doto (WGPUColorTargetState/allocate (Arena/global))
    (WGPUColorTargetState/format bgra8-unorm-srgb)
    (WGPUColorTargetState/writeMask (wgpu-constant "WGPUColorWriteMask_All"))))

(defn fragment-state!
  "Build a WGPUFragmentState pointing at the shader module and one
  colour target, with the given fragment entry point."
  ([shader-module color-target]
   (fragment-state! shader-module color-target "fragment_main"))
  ([shader-module color-target entry-point]
   (doto (WGPUFragmentState/allocate (Arena/global))
     (WGPUFragmentState/module (ffi/pointer shader-module))
     (WGPUFragmentState/entryPoint (ffi/string! entry-point))
     (WGPUFragmentState/targetCount 1)
     (WGPUFragmentState/targets (ffi/pointer color-target)))))

(defn- primitive-state!
  "A WGPUPrimitiveState drawing triangle lists, with default
  front-face, cull and strip-index settings."
  []
  (doto (WGPUPrimitiveState/allocate (Arena/global))
    (WGPUPrimitiveState/topology (wgpu-constant "WGPUPrimitiveTopology_TriangleList"))))

(defn- multisample-state!
  "A WGPUMultisampleState: one sample, the full 32-bit sample mask."
  []
  (doto (WGPUMultisampleState/allocate (Arena/global))
    (WGPUMultisampleState/count 1)
    (WGPUMultisampleState/mask (int -1))))

(defn render-pipeline-descriptor!
  "Build a WGPURenderPipelineDescriptor for the triangle shader. The
  vertex, primitive and multisample states live inside it by value;
  fragment points at its own struct. Automatic bind group layout:
  layout stays NULL."
  [shader-module fragment-state]
  (doto (WGPURenderPipelineDescriptor/allocate (Arena/global))
    (WGPURenderPipelineDescriptor/vertex
     (doto (WGPUVertexState/allocate (Arena/global))
         (WGPUVertexState/module (ffi/pointer shader-module))
         (WGPUVertexState/entryPoint (ffi/string! "vertex_main"))))
    (WGPURenderPipelineDescriptor/primitive (primitive-state!))
    (WGPURenderPipelineDescriptor/multisample (multisample-state!))
    (WGPURenderPipelineDescriptor/fragment (ffi/pointer fragment-state))))

(defn create-triangle-pipeline!
  "Create the render pipeline for the procedural triangle shader
  (automatic bind group layout, one B8G8R8A8UnormSrgb colour target)."
  [device shader-module]
  (wgpu_h/wgpuDeviceCreateRenderPipeline (ffi/pointer device)
                                         (render-pipeline-descriptor!
                                          shader-module
                                          (fragment-state! shader-module (color-target-state!)))))

;; ── the data-driven pipeline: vertices from a vertex buffer

(def vertex-bytes-per-vertex
  "Stride of one vertex in the vertex buffer: two floats position,
  four floats color."
  24)

(defn- vertex-attributes!
  "Build the two WGPUVertexAttribute entries: position (float32x2) at
  shader location 0, color (float32x4) at shader location 1."
  []
  (let [attributes (WGPUVertexAttribute/allocateArray 2 (Arena/global))]
    (doto (WGPUVertexAttribute/asSlice attributes 0)
          (WGPUVertexAttribute/format float32x2-vertex-format)
          (WGPUVertexAttribute/offset 0)
          (WGPUVertexAttribute/shaderLocation 0))
    (doto (WGPUVertexAttribute/asSlice attributes 1)
          (WGPUVertexAttribute/format float32x4-vertex-format)
          (WGPUVertexAttribute/offset 8)
          (WGPUVertexAttribute/shaderLocation 1))
    attributes))

(defn vertex-buffer-layout!
  "Build a WGPUVertexBufferLayout describing the interleaved 24-byte
  vertex stride. stepMode stays 0, which is Vertex."
  []
  (doto (WGPUVertexBufferLayout/allocate (Arena/global))
    (WGPUVertexBufferLayout/arrayStride (long vertex-bytes-per-vertex))
    (WGPUVertexBufferLayout/attributeCount 2)
    (WGPUVertexBufferLayout/attributes (ffi/pointer (vertex-attributes!)))))

(defn data-render-pipeline-descriptor!
  "Build a WGPURenderPipelineDescriptor for the data-driven triangle
  shader: like render-pipeline-descriptor!, but the vertex state
  names vertex_data_main and carries one vertex buffer layout."
  [shader-module fragment-state buffer-layout]
  (doto (WGPURenderPipelineDescriptor/allocate (Arena/global))
    (WGPURenderPipelineDescriptor/vertex
     (doto (WGPUVertexState/allocate (Arena/global))
         (WGPUVertexState/module (ffi/pointer shader-module))
         (WGPUVertexState/entryPoint (ffi/string! "vertex_data_main"))
         (WGPUVertexState/bufferCount 1)
         (WGPUVertexState/buffers (ffi/pointer buffer-layout))))
    (WGPURenderPipelineDescriptor/primitive (primitive-state!))
    (WGPURenderPipelineDescriptor/multisample (multisample-state!))
    (WGPURenderPipelineDescriptor/fragment (ffi/pointer fragment-state))))

(defn create-data-pipeline!
  "Create the data-driven render pipeline: a vertex buffer carries
  position and color per vertex, one B8G8R8A8UnormSrgb colour target,
  automatic bind group layout."
  [device shader-module]
  (wgpu_h/wgpuDeviceCreateRenderPipeline (ffi/pointer device)
                                         (data-render-pipeline-descriptor!
                                          shader-module
                                          (fragment-state! shader-module (color-target-state!)
                                                           "fragment_data_main")
                                          (vertex-buffer-layout!))))

(defn buffer-descriptor!
  "Build a WGPUBufferDescriptor for a buffer of the given size in
  bytes, by default with COPY_DST usage, so queue-write-buffer can
  fill it and the vertex shader can read it. Pass a different usage
  number to override."
  ([size]
   (buffer-descriptor! vertex-buffer-usage size))
  ([usage size]
   (doto (WGPUBufferDescriptor/allocate (Arena/global))
     (WGPUBufferDescriptor/usage (int usage))
     (WGPUBufferDescriptor/size (long size)))))

;; ── Clojure triangle data -> vertex floats

(defn color-component
  "Read one color component from Clojure data: integers above 1 are
  0..255 and scale down, anything else is already 0..1."
  [component]
  (if (and (integer? component) (> component 1))
    (/ (double component) 255)
    (double component)))

(defn vertex-floats
  "One vertex of Clojure data — [x y r g b], [x y r g b a] or
  [x y [r g b a]] with the color nested (alpha optional) — as the six
  floats the vertex layout wants (alpha defaults to 1)."
  [vertex]
  (let [[x y & more] vertex
        colors (if (sequential? (first more)) (first more) more)
        [r g b a] (take 4 (concat colors [1.0 1.0 1.0]))]
    [(double x) (double y)
     (color-component r) (color-component g)
     (color-component b) (color-component a)]))

(defn triangle-vertices
  "Flatten Clojure triangle data into a flat vector of floats, six per
  vertex: either a flat seq of vertices or a seq of triangles of three
  vertices each."
  [triangles]
  (->> (if (sequential? (first (first triangles)))
         (apply concat triangles)
         triangles)
       (mapcat vertex-floats)
       (into [])))

(deftest test-color-component
  (testing "integers above 1 are 0..255, everything else 0..1"
    (is (= 1.0 (color-component 255)))
    (is (= 0.0 (color-component 0)))
    (is (= 1.0 (color-component 1)))
    (is (= (/ 128.0 255) (color-component 128)))
    (is (= 0.5 (color-component 0.5)))))

(deftest test-vertex-floats
  (testing "five members pad alpha with 1, six pass through"
    (is (= [0.1 0.2 1.0 0.0 (/ 128.0 255) 1.0]
           (vertex-floats [0.1 0.2 255 0 128])))
    (is (= [0.0 0.0 1.0 0.5 0.0 0.25]
           (vertex-floats [0 0 1.0 0.5 0.0 0.25])))
    (is (= [0.5 0.5 (/ 127.0 255) (/ 127.0 255) (/ 127.0 255) 1.0]
           (vertex-floats [0.5 0.5 [127 127 127]])))))

(deftest test-triangle-vertices
  (testing "nested triangles and flat vertices flatten the same"
    (is (= (triangle-vertices [[0 0 255 0 0] [1 0 0 255 0] [0 1 0 0 255]])
           (triangle-vertices [[[0 0 255 0 0] [1 0 0 255 0] [0 1 0 0 255]]])))
    (is (= 36 (count (triangle-vertices
                      [[[0 0 255 0 0] [1 0 0 255 0] [0 1 0 0 255]]
                       [[1 1 0 0 255] [0 1 255 0 0] [1 0 0 255 0]]]))))))

;; ── per-frame plumbing

(defn- as-handle
  "A WGPU handle out of the native memory: nil for NULL, the segment
  otherwise."
  [segment]
  (when (not (.equals segment MemorySegment/NULL)) segment))

(defn acquire-swapchain-texture
  "Call wgpuSurfaceGetCurrentTexture. Returns the acquired texture
  handle (or nil if the swapchain has no free image right now), paired
  with its WGPUSurfaceTexture result buffer."
  [surface]
  (let [result (WGPUSurfaceTexture/allocate (Arena/global))]
    (wgpu_h/wgpuSurfaceGetCurrentTexture (ffi/pointer surface) result)
    [(as-handle (WGPUSurfaceTexture/texture result)) result]))

(defn render-attachment!
  "Build a WGPURenderPassColorAttachment on the given texture view:
  Clear to the demo's dark grey, Store."
  [view]
  (doto (WGPURenderPassColorAttachment/allocate (Arena/global))
    (WGPURenderPassColorAttachment/view (ffi/pointer view))
    (WGPURenderPassColorAttachment/loadOp (wgpu-constant "WGPULoadOp_Clear"))
    (WGPURenderPassColorAttachment/storeOp (wgpu-constant "WGPUStoreOp_Store"))
    (WGPURenderPassColorAttachment/clearValue
     (doto (WGPUColor/allocate (Arena/global))
         (WGPUColor/r 0.09)
         (WGPUColor/g 0.09)
         (WGPUColor/b 0.11)
         (WGPUColor/a 1.0)))))

(defn render-pass-descriptor!
  "Build a WGPURenderPassDescriptor with one colour attachment."
  [attachment]
  (doto (WGPURenderPassDescriptor/allocate (Arena/global))
    (WGPURenderPassDescriptor/colorAttachmentCount 1)
    (WGPURenderPassDescriptor/colorAttachments (ffi/pointer attachment))))

(defn draw-triangle!
  "Record and submit one frame: render pass that clears to a dark grey,
  draws three procedural vertices, then submits and presents. Releases
  everything it created; does nothing when the swapchain has no image."
  [device queue surface pipeline]
  (let [[texture _] (acquire-swapchain-texture surface)]
    (when texture
      (let [view (wgpu_h/wgpuTextureCreateView texture null)
            encoder (wgpu_h/wgpuDeviceCreateCommandEncoder (ffi/pointer device) null)
            pass (wgpu_h/wgpuCommandEncoderBeginRenderPass encoder
                                                           (render-pass-descriptor! (render-attachment! view)))
            _ (wgpu_h/wgpuRenderPassEncoderSetPipeline pass (ffi/pointer pipeline))
            _ (wgpu_h/wgpuRenderPassEncoderDraw pass 3 1 0 0)
            _ (wgpu_h/wgpuRenderPassEncoderEnd pass)
            _ (wgpu_h/wgpuRenderPassEncoderRelease pass)
            command-buffer (wgpu_h/wgpuCommandEncoderFinish encoder null)
            commands (doto (ffi/pointer-array! 1)
                       (ffi/write-pointer! 0 command-buffer))]
        (wgpu_h/wgpuQueueSubmit (ffi/pointer queue) 1 commands)
        (wgpu_h/wgpuSurfacePresent (ffi/pointer surface))
        (wgpu_h/wgpuCommandBufferRelease command-buffer)
        (wgpu_h/wgpuCommandEncoderRelease encoder)
        (wgpu_h/wgpuTextureViewRelease view)
        (wgpu_h/wgpuTextureRelease texture)))))

(defn vertex-data!
  "Copy the flat vertex floats (triangle-vertices) into freshly
  allocated native memory, four bytes each; returns the segment."
  [floats]
  (let [data (ffi/allocate! (* 4 (count floats)))]
    (doseq [[index float-value] (map-indexed vector floats)]
      (ffi/write-f32! data (* 4 index) float-value))
    data))

(defn draw-triangles!
  "Draw the given Clojure triangle data (triangle-vertices) as one
  frame with the data-driven pipeline: the vertices upload into a
  fresh vertex buffer, a render pass clears and draws them, the frame
  presents, everything releases. Positions are clip-space (x right,
  y up, -1..1); a vertex count that is not a multiple of three throws."
  [device queue surface pipeline triangles]
  (let [floats (triangle-vertices triangles)
        vertex-count (quot (count floats) 6)]
    (when-not (zero? (rem vertex-count 3))
      (throw (ex-info "triangle data must hold a multiple of three vertices"
                      {:vertex-count vertex-count})))
    (let [data (vertex-data! floats)
          data-bytes (long (* 4 (count floats)))
          buffer (wgpu_h/wgpuDeviceCreateBuffer (ffi/pointer device)
                                                (buffer-descriptor! data-bytes))]
      (wgpu_h/wgpuQueueWriteBuffer (ffi/pointer queue) buffer 0 data data-bytes)
      (let [[texture _] (acquire-swapchain-texture surface)]
        (when texture
          (let [view (wgpu_h/wgpuTextureCreateView texture null)
                encoder (wgpu_h/wgpuDeviceCreateCommandEncoder (ffi/pointer device) null)
                pass (wgpu_h/wgpuCommandEncoderBeginRenderPass encoder
                                                               (render-pass-descriptor! (render-attachment! view)))]
            (wgpu_h/wgpuRenderPassEncoderSetPipeline pass (ffi/pointer pipeline))
            (wgpu_h/wgpuRenderPassEncoderSetVertexBuffer pass 0 buffer 0 data-bytes)
            (wgpu_h/wgpuRenderPassEncoderDraw pass (int vertex-count) 1 0 0)
            (wgpu_h/wgpuRenderPassEncoderEnd pass)
            (wgpu_h/wgpuRenderPassEncoderRelease pass)
            (let [command-buffer (wgpu_h/wgpuCommandEncoderFinish encoder null)
                  commands (doto (ffi/pointer-array! 1)
                             (ffi/write-pointer! 0 command-buffer))]
              (wgpu_h/wgpuQueueSubmit (ffi/pointer queue) 1 commands)
              (wgpu_h/wgpuSurfacePresent (ffi/pointer surface))
              (wgpu_h/wgpuCommandBufferRelease command-buffer)
              (wgpu_h/wgpuCommandEncoderRelease encoder)
              (wgpu_h/wgpuTextureViewRelease view)
              (wgpu_h/wgpuTextureRelease texture))))
        (wgpu_h/wgpuBufferRelease buffer)))))

(comment
  ;; Shape check (run after loading the library):
  ;; (create-instance!) => non-NULL MemorySegment
  )
